package com.anahuac.rest.api.DB

class StatementsBachillerato {
	public static final String GET = "SELECT * FROM CATBACHILLERATOS ";
	public static final String INSERT = "INSERT INTO CATBACHILLERATOS (PERSISTENCEID,CIUDAD,CLAVE,DESCRIPCION,ESTADO,FECHACREACION,ISELIMINADO,ISENABLED,PAIS,PERSISTENCEVERSION,PERTENECERED,USUARIOBANNER,FECHAIMPORTACION) VALUES ((SELECT CASE WHEN MAX(PERSISTENCEID) is null then 1 else MAX(PERSISTENCEID)+1 end AS id FROM CATBACHILLERATOS),?,?,?,?,NOW(),false,true,?,0,?,?,NOW())"
	public static final String UPDATE = "UPDATE CATBACHILLERATOS SET CIUDAD=?, CLAVE=?, DESCRIPCION=?, ESTADO=?, PAIS=?, USUARIOBANNER=?, ISELIMINADO=?, ISENABLED=? WHERE PERSISTENCEID=?"
	
}
