package com.anahuac.rest.api.DB

class Statements {
	public static final String GET_SOLICITUD_DE_ADMISION_BY_CORREO = "SELECT SAD.primernombre, SAD.segundonombre, SAD.apellidopaterno, SAD.apellidomaterno, SAD.correoelectronico, SAD.fechanacimiento, SAD.telefono, SEX.descripcion AS sexo, CTA.descripcion AS tipoAdmision, CGE.nombre AS licenciatura, CPE.descripcion AS semestre, DET.IDBANNER AS idalumno, CNA.descripcion AS nacionalidad, CTR.descripcion AS trabajas, CEC.descripcion AS estadocivil, SAD.caseid FROM SOLICITUDDEADMISION AS SAD INNER JOIN CATSEXO AS SEX ON SEX.PERSISTENCEID = SAD.CATSEXO_PID INNER JOIN DETALLESOLICITUD AS DET ON DET.CASEID = cast(SAD.CASEID as varchar)  INNER JOIN CATTIPOADMISION AS CTA ON CTA.PERSISTENCEID = DET.CATTIPOADMISION_PID INNER JOIN CATGESTIONESCOLAR AS CGE ON CGE.PERSISTENCEID = SAD.catgestionescolar_pid INNER JOIN CATPERIODO AS CPE ON CPE.PERSISTENCEID = SAD.CATPERIODO_PID INNER JOIN CATNACIONALIDAD AS CNA ON CNA.PERSISTENCEID = SAD.CATNACIONALIDAD_PID INNER JOIN AUTODESCRIPCIONV2 AS AUD ON AUD.CASEID = SAD.CASEID INNER JOIN CATACTUALMENTETRABAJAS AS CTR ON CTR.PERSISTENCEID = AUD.CATACTUALNENTETRABAJAS_PID INNER JOIN CATESTADOCIVIL AS CEC ON CEC.PERSISTENCEID = SAD.CATESTADOCIVIL_PID WHERE CORREOELECTRONICO = ?; ";
	
	public static final String GET_INFORMACION_ESCOLAR_BY_CORREO = "SELECT CBA.descripcion, SAD.promediogeneral AS promedioPreparatoria, CBA.id, CBA.ciudad, CBA.estado, CBA.pais, '' AS costoMensualPReparatoria, SAD.urlconstancia  FROM SOLICITUDDEADMISION AS SAD INNER JOIN CATBACHILLERATOS AS CBA ON CBA.PERSISTENCEID = SAD.CATBACHILLERATOS_PID WHERE CORREOELECTRONICO = ?;";
	
	public static final String GET_PADRES_TUTOT_BY_CASEID = "SELECT * FROM PADRESTUTOR WHERE CASEID = ?";
}
