<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:actormapping="http://www.bonitasoft.org/ns/actormapping/6.0" xmlns:configuration="http://www.bonitasoft.org/ns/studio/configuration" xmlns:connectorconfiguration="http://wwww.bonitasoft.org/model/connector/configuration" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:definition="http://www.bonitasoft.org/ns/connector/definition/6.1" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.2/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_HMxucFauEeuD6v1bYMZP8Q" name="PadreMadreTest" author="jasz1" bonitaVersion="7.11.2" bonitaModelVersion="7.11.1-001" configId="ACED000574002050616472654D6164726554657374372E31312E312D303031372E31312E327370">
    <elements xmi:type="process:Pool" xmi:id="_HMxucVauEeuD6v1bYMZP8Q" name="PadreMadreTest">
      <elements xmi:type="process:Lane" xmi:id="_HMxuclauEeuD6v1bYMZP8Q" name="Empleado (lane) " actor="_HMxui1auEeuD6v1bYMZP8Q">
        <elements xmi:type="process:StartEvent" xmi:id="_HMxuc1auEeuD6v1bYMZP8Q" name="Inicio1" outgoing="_HMxuiFauEeuD6v1bYMZP8Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_HMxudFauEeuD6v1bYMZP8Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_HMxudVauEeuD6v1bYMZP8Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_HMxudlauEeuD6v1bYMZP8Q" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_WmVwQGgDEeuSjcrVjSooiw" name="Tarea1" outgoing="_TaP2gGc5EeuoDbTQ9HEyNA" incoming="_HMxuiFauEeuD6v1bYMZP8Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_HMxueFauEeuD6v1bYMZP8Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_HMxueVauEeuD6v1bYMZP8Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_HMxuelauEeuD6v1bYMZP8Q" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_-hr90GsKEeuWI54NqObC_w" name="getCookie()" definitionId="rest-post" event="ON_ENTER" ignoreErrors="true" definitionVersion="1.1.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_-hr90WsKEeuWI54NqObC_w" definitionId="rest-post" version="1.1.0" modelVersion="7.11.1-001">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-hr90msKEeuWI54NqObC_w" key="url">
                <expression xmi:type="expression:Expression" xmi:id="_-hr902sKEeuWI54NqObC_w" name="url()" content="String resultado = &quot;https://anahuac-preproduction.bonitacloud.com/loginservice?redirectUrl=portal%2Fhomepage&amp;username=[USUARIO]&amp;password=[PASSWORD]&amp;_l=es&quot;;&#xD;&#xA;&#xD;&#xA;resultado = resultado.replace(&quot;[USUARIO]&quot;, &quot;Administrador&quot;);&#xD;&#xA;resultado = resultado.replace(&quot;[PASSWORD]&quot;, &quot;bpm&quot;);&#xD;&#xA;&#xD;&#xA;return resultado;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-hr91GsKEeuWI54NqObC_w" key="contentType">
                <expression xmi:type="expression:Expression" xmi:id="_-hr91WsKEeuWI54NqObC_w" name="application/json" content="application/json" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-hr91msKEeuWI54NqObC_w" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_-hr912sKEeuWI54NqObC_w" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-hr92GsKEeuWI54NqObC_w" key="urlCookies">
                <expression xmi:type="expression:TableExpression" xmi:id="_-hr92WsKEeuWI54NqObC_w"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-hr92msKEeuWI54NqObC_w" key="urlHeaders">
                <expression xmi:type="expression:TableExpression" xmi:id="_-hr922sKEeuWI54NqObC_w"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-hr93GsKEeuWI54NqObC_w" key="body">
                <expression xmi:type="expression:Expression" xmi:id="_-hr93WsKEeuWI54NqObC_w" name="&lt;pattern-expression>" type="TYPE_PATTERN" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-hr93msKEeuWI54NqObC_w" key="do_not_follow_redirect">
                <expression xmi:type="expression:Expression" xmi:id="_-hr932sKEeuWI54NqObC_w" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-hr94GsKEeuWI54NqObC_w" key="ignore_body">
                <expression xmi:type="expression:Expression" xmi:id="_-hr94WsKEeuWI54NqObC_w" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-hr94msKEeuWI54NqObC_w" key="TLS">
                <expression xmi:type="expression:Expression" xmi:id="_-hr942sKEeuWI54NqObC_w" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-hr95GsKEeuWI54NqObC_w" key="trust_self_signed_certificate">
                <expression xmi:type="expression:Expression" xmi:id="_-hr95WsKEeuWI54NqObC_w" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-hr95msKEeuWI54NqObC_w" key="hostname_verifier">
                <expression xmi:type="expression:Expression" xmi:id="_-hr952sKEeuWI54NqObC_w" name="Strict" content="Strict" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-hr96GsKEeuWI54NqObC_w" key="trust_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_-hr96WsKEeuWI54NqObC_w" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-hr96msKEeuWI54NqObC_w" key="trust_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_-hr962sKEeuWI54NqObC_w" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-hr97GsKEeuWI54NqObC_w" key="key_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_-hr97WsKEeuWI54NqObC_w" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-hr97msKEeuWI54NqObC_w" key="key_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_-hr972sKEeuWI54NqObC_w" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-hr98GsKEeuWI54NqObC_w" key="auth_type">
                <expression xmi:type="expression:Expression" xmi:id="_-hr98WsKEeuWI54NqObC_w" name="NONE" content="NONE" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-hr98msKEeuWI54NqObC_w" key="auth_username">
                <expression xmi:type="expression:Expression" xmi:id="_-hr982sKEeuWI54NqObC_w" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-hr99GsKEeuWI54NqObC_w" key="auth_password">
                <expression xmi:type="expression:Expression" xmi:id="_-hr99WsKEeuWI54NqObC_w" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-hr99msKEeuWI54NqObC_w" key="auth_host">
                <expression xmi:type="expression:Expression" xmi:id="_-hr992sKEeuWI54NqObC_w" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-hr9-GsKEeuWI54NqObC_w" key="auth_port">
                <expression xmi:type="expression:Expression" xmi:id="_-hr9-WsKEeuWI54NqObC_w" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-hr9-msKEeuWI54NqObC_w" key="auth_realm">
                <expression xmi:type="expression:Expression" xmi:id="_-hr9-2sKEeuWI54NqObC_w" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-hr9_GsKEeuWI54NqObC_w" key="auth_preemptive">
                <expression xmi:type="expression:Expression" xmi:id="_-hr9_WsKEeuWI54NqObC_w" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-hr9_msKEeuWI54NqObC_w" key="proxy_protocol">
                <expression xmi:type="expression:Expression" xmi:id="_-hr9_2sKEeuWI54NqObC_w" name="HTTP" content="HTTP" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-hr-AGsKEeuWI54NqObC_w" key="proxy_host">
                <expression xmi:type="expression:Expression" xmi:id="_-hr-AWsKEeuWI54NqObC_w" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-hr-AmsKEeuWI54NqObC_w" key="proxy_port">
                <expression xmi:type="expression:Expression" xmi:id="_-hr-A2sKEeuWI54NqObC_w" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-hr-BGsKEeuWI54NqObC_w" key="proxy_username">
                <expression xmi:type="expression:Expression" xmi:id="_-hr-BWsKEeuWI54NqObC_w" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-hr-BmsKEeuWI54NqObC_w" key="proxy_password">
                <expression xmi:type="expression:Expression" xmi:id="_-hr-B2sKEeuWI54NqObC_w" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-hr-CGsKEeuWI54NqObC_w" key="socket_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_-hr-CWsKEeuWI54NqObC_w" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-hr-CmsKEeuWI54NqObC_w" key="connection_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_-hr-C2sKEeuWI54NqObC_w" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
            </configuration>
            <outputs xmi:type="expression:Operation" xmi:id="_Ye8KAGsLEeuWI54NqObC_w">
              <leftOperand xmi:type="expression:Expression" xmi:id="_Ye8KAWsLEeuWI54NqObC_w" name="cookie" content="cookie" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_Ye8KAmsLEeuWI54NqObC_w" name="cookie" dataType="_HMxuoVauEeuD6v1bYMZP8Q"/>
              </leftOperand>
              <rightOperand xmi:type="expression:Expression" xmi:id="_Ye8KA2sLEeuWI54NqObC_w" name="Set-Cookie()" content="return headers.get(&quot;Set-Cookie&quot;);" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                <referencedElements xmi:type="definition:Output" xmi:id="_Ye8KBGsLEeuWI54NqObC_w" name="headers" type="java.util.Map"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_Ye8KBWsLEeuWI54NqObC_w" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_Ye8xEGsLEeuWI54NqObC_w">
              <leftOperand xmi:type="expression:Expression" xmi:id="_Ye8xEWsLEeuWI54NqObC_w" name="xApiBonitaToken" content="xApiBonitaToken" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_Ye8xEmsLEeuWI54NqObC_w" name="xApiBonitaToken" dataType="_HMxuoVauEeuD6v1bYMZP8Q"/>
              </leftOperand>
              <rightOperand xmi:type="expression:Expression" xmi:id="_Ye8xE2sLEeuWI54NqObC_w" name="xApiBonita()" content="String header = headers.get(&quot;Set-Cookie&quot;);&#xD;&#xA;List&lt;String> lstCookie = new ArrayList&lt;String>();&#xD;&#xA;String resultado = &quot;&quot;;&#xD;&#xA;try {&#xD;&#xA;&#x9;lstCookie = Arrays.asList(header.split(&quot;;&quot;));&#xD;&#xA;&#x9;for(String obj : lstCookie) {&#xD;&#xA;&#x9;&#x9;if(obj.contains(&quot;X-Bonita-API-Token&quot;)) {&#xD;&#xA;&#x9;&#x9;&#x9;resultado = (obj.substring(obj.indexOf(&quot;=&quot;)+1));&#xD;&#xA;&#x9;&#x9;&#x9;break;&#xD;&#xA;&#x9;&#x9;}&#xD;&#xA;&#x9;}&#xD;&#xA;} catch (Exception e) {&#xD;&#xA;&#x9;resultado = e.getMessage();&#xD;&#xA;}&#xD;&#xA;&#xD;&#xA;return resultado;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                <referencedElements xmi:type="definition:Output" xmi:id="_Ye8xFGsLEeuWI54NqObC_w" name="headers" type="java.util.Map"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_Ye8xFWsLEeuWI54NqObC_w" type="ASSIGNMENT"/>
            </outputs>
          </connectors>
          <connectors xmi:type="process:Connector" xmi:id="_LGK8oGsMEeuWI54NqObC_w" name="getLastFechaExamenByUsername();" definitionId="rest-post" event="ON_ENTER" ignoreErrors="true" definitionVersion="1.1.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_LGK8oWsMEeuWI54NqObC_w" definitionId="rest-post" version="1.1.0" modelVersion="7.11.1-001">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_LGK8omsMEeuWI54NqObC_w" key="url">
                <expression xmi:type="expression:Expression" xmi:id="_LGK8o2sMEeuWI54NqObC_w" name="url()" content="return &quot;https://anahuac-preproduction.bonitacloud.com/API/extension/AnahuacRest?url=getLastFechaExamenByUsername&amp;p=0&amp;c=10&quot;;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_LGK8pGsMEeuWI54NqObC_w" key="contentType">
                <expression xmi:type="expression:Expression" xmi:id="_LGK8pWsMEeuWI54NqObC_w" name="application/json" content="application/json" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_LGK8pmsMEeuWI54NqObC_w" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_LGK8p2sMEeuWI54NqObC_w" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_LGK8qGsMEeuWI54NqObC_w" key="urlCookies">
                <expression xmi:type="expression:TableExpression" xmi:id="_LGK8qWsMEeuWI54NqObC_w"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_LGK8qmsMEeuWI54NqObC_w" key="urlHeaders">
                <expression xmi:type="expression:TableExpression" xmi:id="_LGK8q2sMEeuWI54NqObC_w">
                  <expressions xmi:type="expression:ListExpression" xmi:id="_s_OhwGsMEeuWI54NqObC_w">
                    <expressions xmi:type="expression:Expression" xmi:id="_s_OhwWsMEeuWI54NqObC_w" name="Cookie()" content="return &quot;Cookie&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT"/>
                    <expressions xmi:type="expression:Expression" xmi:id="_s_OhwmsMEeuWI54NqObC_w" name="newScript()" content="return cookie;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                      <referencedElements xmi:type="process:Data" xmi:id="_s_Ohw2sMEeuWI54NqObC_w" name="cookie" dataType="_HMxuoVauEeuD6v1bYMZP8Q"/>
                    </expressions>
                  </expressions>
                  <expressions xmi:type="expression:ListExpression" xmi:id="_s_PI0GsMEeuWI54NqObC_w">
                    <expressions xmi:type="expression:Expression" xmi:id="_s_PI0WsMEeuWI54NqObC_w" name="X-Bonita-API-Token()" content="return &quot;X-Bonita-API-Token&quot;;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT"/>
                    <expressions xmi:type="expression:Expression" xmi:id="_s_PI0msMEeuWI54NqObC_w" name="newScript()" content="return xApiBonitaToken;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                      <referencedElements xmi:type="process:Data" xmi:id="_s_PI02sMEeuWI54NqObC_w" name="xApiBonitaToken" dataType="_HMxuoVauEeuD6v1bYMZP8Q"/>
                    </expressions>
                  </expressions>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_LGK8rGsMEeuWI54NqObC_w" key="body">
                <expression xmi:type="expression:Expression" xmi:id="_LGK8rWsMEeuWI54NqObC_w" name="body()" content="String payload = &quot;{\&quot;username\&quot;: \&quot;[USERNAME]\&quot;}&quot;;&#xD;&#xA;payload = payload.replace(&quot;[USERNAME]&quot;, username);&#xD;&#xA;&#xD;&#xA;return payload;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="process:Data" xmi:id="_s_Pv4GsMEeuWI54NqObC_w" name="username" dataType="_HMxuoVauEeuD6v1bYMZP8Q"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_LGK8rmsMEeuWI54NqObC_w" key="do_not_follow_redirect">
                <expression xmi:type="expression:Expression" xmi:id="_LGK8r2sMEeuWI54NqObC_w" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_LGK8sGsMEeuWI54NqObC_w" key="ignore_body">
                <expression xmi:type="expression:Expression" xmi:id="_LGK8sWsMEeuWI54NqObC_w" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_LGK8smsMEeuWI54NqObC_w" key="TLS">
                <expression xmi:type="expression:Expression" xmi:id="_LGK8s2sMEeuWI54NqObC_w" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_LGK8tGsMEeuWI54NqObC_w" key="trust_self_signed_certificate">
                <expression xmi:type="expression:Expression" xmi:id="_LGK8tWsMEeuWI54NqObC_w" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_LGK8tmsMEeuWI54NqObC_w" key="hostname_verifier">
                <expression xmi:type="expression:Expression" xmi:id="_LGK8t2sMEeuWI54NqObC_w" name="Strict" content="Strict" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_LGK8uGsMEeuWI54NqObC_w" key="trust_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_LGK8uWsMEeuWI54NqObC_w" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_LGK8umsMEeuWI54NqObC_w" key="trust_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_LGK8u2sMEeuWI54NqObC_w" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_LGK8vGsMEeuWI54NqObC_w" key="key_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_LGK8vWsMEeuWI54NqObC_w" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_LGK8vmsMEeuWI54NqObC_w" key="key_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_LGK8v2sMEeuWI54NqObC_w" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_LGK8wGsMEeuWI54NqObC_w" key="auth_type">
                <expression xmi:type="expression:Expression" xmi:id="_LGK8wWsMEeuWI54NqObC_w" name="NONE" content="NONE" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_LGK8wmsMEeuWI54NqObC_w" key="auth_username">
                <expression xmi:type="expression:Expression" xmi:id="_LGK8w2sMEeuWI54NqObC_w" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_LGK8xGsMEeuWI54NqObC_w" key="auth_password">
                <expression xmi:type="expression:Expression" xmi:id="_LGK8xWsMEeuWI54NqObC_w" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_LGK8xmsMEeuWI54NqObC_w" key="auth_host">
                <expression xmi:type="expression:Expression" xmi:id="_LGK8x2sMEeuWI54NqObC_w" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_LGK8yGsMEeuWI54NqObC_w" key="auth_port">
                <expression xmi:type="expression:Expression" xmi:id="_LGK8yWsMEeuWI54NqObC_w" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_LGK8ymsMEeuWI54NqObC_w" key="auth_realm">
                <expression xmi:type="expression:Expression" xmi:id="_LGK8y2sMEeuWI54NqObC_w" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_LGK8zGsMEeuWI54NqObC_w" key="auth_preemptive">
                <expression xmi:type="expression:Expression" xmi:id="_LGK8zWsMEeuWI54NqObC_w" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_LGK8zmsMEeuWI54NqObC_w" key="proxy_protocol">
                <expression xmi:type="expression:Expression" xmi:id="_LGK8z2sMEeuWI54NqObC_w" name="HTTP" content="HTTP" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_LGK80GsMEeuWI54NqObC_w" key="proxy_host">
                <expression xmi:type="expression:Expression" xmi:id="_LGK80WsMEeuWI54NqObC_w" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_LGK80msMEeuWI54NqObC_w" key="proxy_port">
                <expression xmi:type="expression:Expression" xmi:id="_LGK802sMEeuWI54NqObC_w" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_LGK81GsMEeuWI54NqObC_w" key="proxy_username">
                <expression xmi:type="expression:Expression" xmi:id="_LGK81WsMEeuWI54NqObC_w" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_LGK81msMEeuWI54NqObC_w" key="proxy_password">
                <expression xmi:type="expression:Expression" xmi:id="_LGK812sMEeuWI54NqObC_w" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_LGK82GsMEeuWI54NqObC_w" key="socket_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_LGK82WsMEeuWI54NqObC_w" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_LGK82msMEeuWI54NqObC_w" key="connection_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_LGK822sMEeuWI54NqObC_w" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
            </configuration>
            <outputs xmi:type="expression:Operation" xmi:id="_s_SMIGsMEeuWI54NqObC_w">
              <leftOperand xmi:type="expression:Expression" xmi:id="_s_SMIWsMEeuWI54NqObC_w" name="objPrueba1" content="objPrueba1" type="TYPE_VARIABLE" returnType="java.util.Map">
                <referencedElements xmi:type="process:JavaObjectData" xmi:id="_s_SMImsMEeuWI54NqObC_w" name="objPrueba1" dataType="_HMxuolauEeuD6v1bYMZP8Q" className="java.util.Map"/>
              </leftOperand>
              <rightOperand xmi:type="expression:Expression" xmi:id="_s_SMI2sMEeuWI54NqObC_w" name="resultado1" content="import groovy.json.JsonBuilder&#xD;&#xA;import groovy.json.JsonSlurper&#xD;&#xA;&#xD;&#xA;Map&lt;String, Object> resultado=new HashMap&lt;String, Object>();&#xD;&#xA;&#xD;&#xA;def jsonSlurper = new JsonSlurper();&#xD;&#xA;def object = jsonSlurper.parseText(bodyAsString);&#xD;&#xA;&#xD;&#xA;assert object instanceof Map&#xD;&#xA;&#xD;&#xA;assert object.data instanceof List&#xD;&#xA;for(def row : object.data) {&#xD;&#xA;&#x9;assert row instanceof Map&#xD;&#xA;&#x9;if(row.contador.toString() == &quot;1&quot;){&#xD;&#xA;&#x9;&#x9;resultado.put(&quot;contador&quot;, row.contador);&#xD;&#xA;&#x9;&#x9;resultado.put(&quot;tiempo&quot;, row.tiempo);&#xD;&#xA;&#x9;&#x9;resultado.put(&quot;descripcion&quot;, row.descripcion);&#xD;&#xA;&#x9;}&#xD;&#xA;}&#xD;&#xA;&#xD;&#xA;return resultado;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.Map">
                <referencedElements xmi:type="definition:Output" xmi:id="_s_SMJGsMEeuWI54NqObC_w" name="bodyAsString" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_s_SMJWsMEeuWI54NqObC_w" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_s_SMJmsMEeuWI54NqObC_w">
              <leftOperand xmi:type="expression:Expression" xmi:id="_s_SMJ2sMEeuWI54NqObC_w" name="objPrueba2" content="objPrueba2" type="TYPE_VARIABLE" returnType="java.util.Map">
                <referencedElements xmi:type="process:JavaObjectData" xmi:id="_s_SMKGsMEeuWI54NqObC_w" name="objPrueba2" dataType="_HMxuolauEeuD6v1bYMZP8Q" className="java.util.Map"/>
              </leftOperand>
              <rightOperand xmi:type="expression:Expression" xmi:id="_s_SMKWsMEeuWI54NqObC_w" name="resultado2" content="import groovy.json.JsonBuilder&#xD;&#xA;import groovy.json.JsonSlurper&#xD;&#xA;&#xD;&#xA;Map&lt;String, Object> resultado=new HashMap&lt;String, Object>();&#xD;&#xA;&#xD;&#xA;def jsonSlurper = new JsonSlurper();&#xD;&#xA;def object = jsonSlurper.parseText(bodyAsString);&#xD;&#xA;&#xD;&#xA;assert object instanceof Map&#xD;&#xA;&#xD;&#xA;assert object.data instanceof List&#xD;&#xA;for(def row : object.data) {&#xD;&#xA;&#x9;assert row instanceof Map&#xD;&#xA;&#x9;if(row.contador.toString() == &quot;2&quot;){&#xD;&#xA;&#x9;&#x9;resultado.put(&quot;contador&quot;, row.contador);&#xD;&#xA;&#x9;&#x9;resultado.put(&quot;tiempo&quot;, row.tiempo);&#xD;&#xA;&#x9;&#x9;resultado.put(&quot;descripcion&quot;, row.descripcion);&#xD;&#xA;&#x9;}&#xD;&#xA;}&#xD;&#xA;&#xD;&#xA;return resultado;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.Map">
                <referencedElements xmi:type="definition:Output" xmi:id="_s_SMKmsMEeuWI54NqObC_w" name="bodyAsString" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_s_SMK2sMEeuWI54NqObC_w" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_s_SMLGsMEeuWI54NqObC_w">
              <leftOperand xmi:type="expression:Expression" xmi:id="_s_SMLWsMEeuWI54NqObC_w" name="objPrueba3" content="objPrueba3" type="TYPE_VARIABLE" returnType="java.util.Map">
                <referencedElements xmi:type="process:JavaObjectData" xmi:id="_s_SMLmsMEeuWI54NqObC_w" name="objPrueba3" dataType="_HMxuolauEeuD6v1bYMZP8Q" className="java.util.Map"/>
              </leftOperand>
              <rightOperand xmi:type="expression:Expression" xmi:id="_s_SML2sMEeuWI54NqObC_w" name="resultado3" content="import groovy.json.JsonBuilder&#xD;&#xA;import groovy.json.JsonSlurper&#xD;&#xA;&#xD;&#xA;Map&lt;String, Object> resultado=new HashMap&lt;String, Object>();&#xD;&#xA;&#xD;&#xA;def jsonSlurper = new JsonSlurper();&#xD;&#xA;def object = jsonSlurper.parseText(bodyAsString);&#xD;&#xA;&#xD;&#xA;assert object instanceof Map&#xD;&#xA;&#xD;&#xA;assert object.data instanceof List&#xD;&#xA;for(def row : object.data) {&#xD;&#xA;&#x9;assert row instanceof Map&#xD;&#xA;&#x9;if(row.contador.toString() == &quot;3&quot;){&#xD;&#xA;&#x9;&#x9;resultado.put(&quot;contador&quot;, row.contador);&#xD;&#xA;&#x9;&#x9;resultado.put(&quot;tiempo&quot;, row.tiempo);&#xD;&#xA;&#x9;&#x9;resultado.put(&quot;descripcion&quot;, row.descripcion);&#xD;&#xA;&#x9;}&#xD;&#xA;}&#xD;&#xA;&#xD;&#xA;return resultado;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.Map">
                <referencedElements xmi:type="definition:Output" xmi:id="_s_SMMGsMEeuWI54NqObC_w" name="bodyAsString" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_s_SMMWsMEeuWI54NqObC_w" type="ASSIGNMENT"/>
            </outputs>
          </connectors>
          <operations xmi:type="expression:Operation" xmi:id="_Sa4D4GsNEeuWI54NqObC_w">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Sa4D4WsNEeuWI54NqObC_w" name="fechaPrueba1" content="fechaPrueba1" type="TYPE_VARIABLE" returnType="java.util.Date">
              <referencedElements xmi:type="process:Data" xmi:id="_TWn6cGsNEeuWI54NqObC_w" name="fechaPrueba1" dataType="_HMxunVauEeuD6v1bYMZP8Q"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Sa4D4msNEeuWI54NqObC_w" name="newScript()" content="Long tsDate = (objPrueba1.get(&quot;tiempo&quot;) == null ? 0L : Long.valueOf(objPrueba1.get(&quot;tiempo&quot;).toString()))&#xD;&#xA;return new Date(tsDate);" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.Date">
              <referencedElements xmi:type="process:JavaObjectData" xmi:id="_Xv0IQGsNEeuWI54NqObC_w" name="objPrueba1" dataType="_HMxuolauEeuD6v1bYMZP8Q" className="java.util.Map"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Sa4D42sNEeuWI54NqObC_w" type="ASSIGNMENT"/>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Sjl7AGsNEeuWI54NqObC_w">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Sjl7AWsNEeuWI54NqObC_w" name="fechaPrueba2" content="fechaPrueba2" type="TYPE_VARIABLE" returnType="java.util.Date">
              <referencedElements xmi:type="process:Data" xmi:id="_T5bFgGsNEeuWI54NqObC_w" name="fechaPrueba2" dataType="_HMxunVauEeuD6v1bYMZP8Q"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Sjl7AmsNEeuWI54NqObC_w" name="newScript()" content="Long tsDate = (objPrueba2.get(&quot;tiempo&quot;) == null ? 0L : Long.valueOf(objPrueba2.get(&quot;tiempo&quot;).toString()))&#xD;&#xA;return new Date(tsDate);" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.Date">
              <referencedElements xmi:type="process:JavaObjectData" xmi:id="_aO-SUGsNEeuWI54NqObC_w" name="objPrueba2" dataType="_HMxuolauEeuD6v1bYMZP8Q" className="java.util.Map"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Sjl7A2sNEeuWI54NqObC_w" type="ASSIGNMENT"/>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Ss6PEGsNEeuWI54NqObC_w">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Ss6PEWsNEeuWI54NqObC_w" name="fechaPrueba3" content="fechaPrueba3" type="TYPE_VARIABLE" returnType="java.util.Date">
              <referencedElements xmi:type="process:Data" xmi:id="_UN0BIGsNEeuWI54NqObC_w" name="fechaPrueba3" dataType="_HMxunVauEeuD6v1bYMZP8Q"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Ss6PEmsNEeuWI54NqObC_w" name="newScript()" content="Long tsDate = (objPrueba3.get(&quot;tiempo&quot;) == null ? 0L : Long.valueOf(objPrueba3.get(&quot;tiempo&quot;).toString()))&#xD;&#xA;return new Date(tsDate);" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.Date">
              <referencedElements xmi:type="process:JavaObjectData" xmi:id="_cao4oGsNEeuWI54NqObC_w" name="objPrueba3" dataType="_HMxuolauEeuD6v1bYMZP8Q" className="java.util.Map"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Ss6PE2sNEeuWI54NqObC_w" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_HMxue1auEeuD6v1bYMZP8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_HMxufFauEeuD6v1bYMZP8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_HMxufVauEeuD6v1bYMZP8Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_HMxuflauEeuD6v1bYMZP8Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_HMxuf1auEeuD6v1bYMZP8Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_XPDWEGgDEeuSjcrVjSooiw" name="Tarea2" outgoing="_Eb81cGsOEeuWI54NqObC_w" incoming="_TaP2gGc5EeuoDbTQ9HEyNA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_XPD9IWgDEeuSjcrVjSooiw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_XPD9IGgDEeuSjcrVjSooiw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_XPD9ImgDEeuSjcrVjSooiw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_XPD9I2gDEeuSjcrVjSooiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_XPD9JGgDEeuSjcrVjSooiw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_XPD9JWgDEeuSjcrVjSooiw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_XPD9J2gDEeuSjcrVjSooiw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_XPD9JmgDEeuSjcrVjSooiw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <BoundaryIntermediateEvents xmi:type="process:BoundaryTimerEvent" xmi:id="_MmbgYGsKEeuWI54NqObC_w" name="Boundary Temporizador1" outgoing="_NWr4oGsKEeuWI54NqObC_w">
            <condition xmi:type="expression:Expression" xmi:id="_8czDAGsMEeuWI54NqObC_w" name="fechaPrueba1" content="return fechaPrueba1;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.Date">
              <referencedElements xmi:type="process:Data" xmi:id="_I68lwGsNEeuWI54NqObC_w" name="fechaPrueba1" dataType="_HMxunVauEeuD6v1bYMZP8Q"/>
            </condition>
          </BoundaryIntermediateEvents>
          <formMapping xmi:type="process:FormMapping" xmi:id="_XPD9KWgDEeuSjcrVjSooiw">
            <targetForm xmi:type="expression:Expression" xmi:id="_VZBakGsOEeuWI54NqObC_w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_XPD9KGgDEeuSjcrVjSooiw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_XPD9K2gDEeuSjcrVjSooiw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_Ogk44GsKEeuWI54NqObC_w" name="Tarea3" outgoing="_Hj9vQGsOEeuWI54NqObC_w" incoming="_VangkGsPEeuWI54NqObC_w" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_NWaL0msKEeuWI54NqObC_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_NWaL0WsKEeuWI54NqObC_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_NWaL02sKEeuWI54NqObC_w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_NWaL1GsKEeuWI54NqObC_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_NWaL1WsKEeuWI54NqObC_w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_NWaL1msKEeuWI54NqObC_w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_NWay4WsKEeuWI54NqObC_w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_NWay4GsKEeuWI54NqObC_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <BoundaryIntermediateEvents xmi:type="process:BoundaryTimerEvent" xmi:id="_O8D7AGsKEeuWI54NqObC_w" name="Boundary Temporizador2" outgoing="_PXONAGsKEeuWI54NqObC_w">
            <condition xmi:type="expression:Expression" xmi:id="__ZxxgGsMEeuWI54NqObC_w" name="fechaPrueba2" content="return fechaPrueba2;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.Date">
              <referencedElements xmi:type="process:Data" xmi:id="_DWFPAGsNEeuWI54NqObC_w" name="fechaPrueba2" dataType="_HMxunVauEeuD6v1bYMZP8Q"/>
            </condition>
          </BoundaryIntermediateEvents>
          <formMapping xmi:type="process:FormMapping" xmi:id="_OgmHAGsKEeuWI54NqObC_w">
            <targetForm xmi:type="expression:Expression" xmi:id="_VZBakWsOEeuWI54NqObC_w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_Oglf-GsKEeuWI54NqObC_w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_OgmHAmsKEeuWI54NqObC_w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_PsyNUGsKEeuWI54NqObC_w" name="Tarea4" outgoing="_F9sVAGsOEeuWI54NqObC_w" incoming="_b_LZwGsPEeuWI54NqObC_w" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_PXJ7kmsKEeuWI54NqObC_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_PXJ7kWsKEeuWI54NqObC_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_PXJ7k2sKEeuWI54NqObC_w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_PXJ7lGsKEeuWI54NqObC_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_PXJ7lWsKEeuWI54NqObC_w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_PXJ7lmsKEeuWI54NqObC_w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_PXJ7mGsKEeuWI54NqObC_w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_PXJ7l2sKEeuWI54NqObC_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <BoundaryIntermediateEvents xmi:type="process:BoundaryTimerEvent" xmi:id="_QLqhsGsKEeuWI54NqObC_w" name="Boundary Temporizador3" outgoing="_RcWtgGsKEeuWI54NqObC_w">
            <condition xmi:type="expression:Expression" xmi:id="_D64lMGsNEeuWI54NqObC_w" name="fechaPrueba3" content="return fechaPrueba3;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.Date">
              <referencedElements xmi:type="process:Data" xmi:id="_F0DGQGsNEeuWI54NqObC_w" name="fechaPrueba3" dataType="_HMxunVauEeuD6v1bYMZP8Q"/>
            </condition>
          </BoundaryIntermediateEvents>
          <formMapping xmi:type="process:FormMapping" xmi:id="_PsyNWmsKEeuWI54NqObC_w">
            <targetForm xmi:type="expression:Expression" xmi:id="_VZBakmsOEeuWI54NqObC_w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_PsyNWWsKEeuWI54NqObC_w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_PsyNXGsKEeuWI54NqObC_w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_S1MvwGsKEeuWI54NqObC_w" name="Fin1" incoming="_S1TdcGsKEeuWI54NqObC_w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_S1MvwmsKEeuWI54NqObC_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_S1MvwWsKEeuWI54NqObC_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_S1NW0GsKEeuWI54NqObC_w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_La0sEGsOEeuWI54NqObC_w" name="Compuerta1" outgoing="_ItOdYGsOEeuWI54NqObC_w" incoming="_Eb81cGsOEeuWI54NqObC_w _F9sVAGsOEeuWI54NqObC_w _Hj9vQGsOEeuWI54NqObC_w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Ebx2UmsOEeuWI54NqObC_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Ebx2UWsOEeuWI54NqObC_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_EbydYGsOEeuWI54NqObC_w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_MyaKEGsOEeuWI54NqObC_w" name="Fin2" incoming="_MydNYGsOEeuWI54NqObC_w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_MyaKEmsOEeuWI54NqObC_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_MyaKEWsOEeuWI54NqObC_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_MyaKE2sOEeuWI54NqObC_w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_Nr4IsGsOEeuWI54NqObC_w" name="Avanzar" outgoing="_MydNYGsOEeuWI54NqObC_w" incoming="_ItOdYGsOEeuWI54NqObC_w" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ItLaEWsOEeuWI54NqObC_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ItLaEGsOEeuWI54NqObC_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ItLaEmsOEeuWI54NqObC_w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_ItLaE2sOEeuWI54NqObC_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_ItLaFGsOEeuWI54NqObC_w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_ItLaFWsOEeuWI54NqObC_w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_ItLaF2sOEeuWI54NqObC_w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_ItLaFmsOEeuWI54NqObC_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_Nr4vyWsOEeuWI54NqObC_w">
            <targetForm xmi:type="expression:Expression" xmi:id="_VZBak2sOEeuWI54NqObC_w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_Nr4vyGsOEeuWI54NqObC_w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_Nr4vy2sOEeuWI54NqObC_w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_OGIbwGsOEeuWI54NqObC_w" name="success" outgoing="_S1TdcGsKEeuWI54NqObC_w" incoming="_foGoQGsPEeuWI54NqObC_w" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_RcScEmsKEeuWI54NqObC_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_RcScEWsKEeuWI54NqObC_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_RcScE2sKEeuWI54NqObC_w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_RcScFGsKEeuWI54NqObC_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_RcScFWsKEeuWI54NqObC_w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_RcScFmsKEeuWI54NqObC_w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_RcScGGsKEeuWI54NqObC_w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_RcScF2sKEeuWI54NqObC_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_OGIbymsOEeuWI54NqObC_w">
            <targetForm xmi:type="expression:Expression" xmi:id="_VZBalGsOEeuWI54NqObC_w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_OGIbyWsOEeuWI54NqObC_w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_OGIbzGsOEeuWI54NqObC_w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_pVvAoGsOEeuWI54NqObC_w" name="Avanzar falta" outgoing="_sXZa0GsOEeuWI54NqObC_w" incoming="_0ck8wGsPEeuWI54NqObC_w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_pVvAomsOEeuWI54NqObC_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_pVvAoWsOEeuWI54NqObC_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_pVvAo2sOEeuWI54NqObC_w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_pVvApGsOEeuWI54NqObC_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_pVvApWsOEeuWI54NqObC_w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_pVvApmsOEeuWI54NqObC_w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_pVvAqGsOEeuWI54NqObC_w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_pVvAp2sOEeuWI54NqObC_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_sXStIGsOEeuWI54NqObC_w" name="Fin3" incoming="_sXZa0GsOEeuWI54NqObC_w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_sXStImsOEeuWI54NqObC_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_sXStIWsOEeuWI54NqObC_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_sXStI2sOEeuWI54NqObC_w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_VaTXgGsPEeuWI54NqObC_w" name="Compuerta3" outgoing="_VangkGsPEeuWI54NqObC_w _aEz-0GsPEeuWI54NqObC_w" incoming="_NWr4oGsKEeuWI54NqObC_w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_VaTXgmsPEeuWI54NqObC_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_VaTXgWsPEeuWI54NqObC_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_VaTXg2sPEeuWI54NqObC_w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ThrowLinkEvent" xmi:id="_aEsqEGsPEeuWI54NqObC_w" name="Enlace1" incoming="_aEz-0GsPEeuWI54NqObC_w" to="_z2MSMGsPEeuWI54NqObC_w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_aEtRIWsPEeuWI54NqObC_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_aEtRIGsPEeuWI54NqObC_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_aEtRImsPEeuWI54NqObC_w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_b_HIUGsPEeuWI54NqObC_w" name="Compuerta4" outgoing="_b_LZwGsPEeuWI54NqObC_w _dd1wIGsPEeuWI54NqObC_w" incoming="_PXONAGsKEeuWI54NqObC_w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_b_HIUmsPEeuWI54NqObC_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_b_HIUWsPEeuWI54NqObC_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_b_HIU2sPEeuWI54NqObC_w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ThrowLinkEvent" xmi:id="_ddvpgGsPEeuWI54NqObC_w" name="Enlace2" incoming="_dd1wIGsPEeuWI54NqObC_w" to="_z2MSMGsPEeuWI54NqObC_w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ddvpgmsPEeuWI54NqObC_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ddvpgWsPEeuWI54NqObC_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ddvpg2sPEeuWI54NqObC_w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_foDk8GsPEeuWI54NqObC_w" name="Compuerta5" outgoing="_foGoQGsPEeuWI54NqObC_w _gmRgsGsPEeuWI54NqObC_w" incoming="_RcWtgGsKEeuWI54NqObC_w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_foDk8msPEeuWI54NqObC_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_foDk8WsPEeuWI54NqObC_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_foDk82sPEeuWI54NqObC_w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ThrowLinkEvent" xmi:id="_gl5tQGsPEeuWI54NqObC_w" name="Enlace3" incoming="_gmRgsGsPEeuWI54NqObC_w" to="_z2MSMGsPEeuWI54NqObC_w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_gl6UUGsPEeuWI54NqObC_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_gl5tQWsPEeuWI54NqObC_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_gl6UUWsPEeuWI54NqObC_w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:CatchLinkEvent" xmi:id="_z2MSMGsPEeuWI54NqObC_w" name="Enlace4" outgoing="_0ck8wGsPEeuWI54NqObC_w" from="_aEsqEGsPEeuWI54NqObC_w _ddvpgGsPEeuWI54NqObC_w _gl5tQGsPEeuWI54NqObC_w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_z2M5QWsPEeuWI54NqObC_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_z2M5QGsPEeuWI54NqObC_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_z2M5QmsPEeuWI54NqObC_w" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:Data" xmi:id="_ickXYGgDEeuSjcrVjSooiw" name="isReagendar" dataType="_HMxunFauEeuD6v1bYMZP8Q">
        <defaultValue xmi:type="expression:Expression" xmi:id="_ickXYWgDEeuSjcrVjSooiw" content="" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_DtmpEGsLEeuWI54NqObC_w" name="xApiBonitaToken" dataType="_HMxuoVauEeuD6v1bYMZP8Q">
        <defaultValue xmi:type="expression:Expression" xmi:id="_DtmpEWsLEeuWI54NqObC_w" content=""/>
      </data>
      <data xmi:type="process:Data" xmi:id="_F7RagGsLEeuWI54NqObC_w" name="cookie" dataType="_HMxuoVauEeuD6v1bYMZP8Q">
        <defaultValue xmi:type="expression:Expression" xmi:id="_F7RagWsLEeuWI54NqObC_w" content=""/>
      </data>
      <data xmi:type="process:JavaObjectData" xmi:id="_4KWy4GsLEeuWI54NqObC_w" name="objPrueba1" dataType="_HMxuolauEeuD6v1bYMZP8Q" className="java.util.Map">
        <defaultValue xmi:type="expression:Expression" xmi:id="_4KWy4WsLEeuWI54NqObC_w" content="" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.Map"/>
      </data>
      <data xmi:type="process:JavaObjectData" xmi:id="_51yZ8GsLEeuWI54NqObC_w" name="objPrueba2" dataType="_HMxuolauEeuD6v1bYMZP8Q" className="java.util.Map">
        <defaultValue xmi:type="expression:Expression" xmi:id="_51yZ8WsLEeuWI54NqObC_w" content="" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.Map"/>
      </data>
      <data xmi:type="process:JavaObjectData" xmi:id="_7wucoGsLEeuWI54NqObC_w" name="objPrueba3" dataType="_HMxuolauEeuD6v1bYMZP8Q" className="java.util.Map">
        <defaultValue xmi:type="expression:Expression" xmi:id="_7wucoWsLEeuWI54NqObC_w" content="" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.Map"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_Mzh2UGsMEeuWI54NqObC_w" name="username" dataType="_HMxuoVauEeuD6v1bYMZP8Q">
        <defaultValue xmi:type="expression:Expression" xmi:id="_Mzh2UWsMEeuWI54NqObC_w" name="usernameCont" content="usernameCont" type="TYPE_CONTRACT_INPUT">
          <referencedElements xmi:type="process:ContractInput" xmi:id="_PcdncGsMEeuWI54NqObC_w" name="usernameCont">
            <mapping xmi:type="process:ContractInputMapping" xmi:id="_PcdncWsMEeuWI54NqObC_w"/>
          </referencedElements>
        </defaultValue>
      </data>
      <data xmi:type="process:Data" xmi:id="_4IqUUGsMEeuWI54NqObC_w" name="fechaPrueba1" dataType="_HMxunVauEeuD6v1bYMZP8Q">
        <defaultValue xmi:type="expression:Expression" xmi:id="_4IqUUWsMEeuWI54NqObC_w" content="" returnType="java.util.Date"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_5Y6bQGsMEeuWI54NqObC_w" name="fechaPrueba2" dataType="_HMxunVauEeuD6v1bYMZP8Q">
        <defaultValue xmi:type="expression:Expression" xmi:id="_5Y6bQWsMEeuWI54NqObC_w" content="" returnType="java.util.Date"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_6rI4IGsMEeuWI54NqObC_w" name="fechaPrueba3" dataType="_HMxunVauEeuD6v1bYMZP8Q">
        <defaultValue xmi:type="expression:Expression" xmi:id="_6rI4IWsMEeuWI54NqObC_w" content="" returnType="java.util.Date"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_33KpwGsOEeuWI54NqObC_w" name="isFalta1" dataType="_HMxunFauEeuD6v1bYMZP8Q">
        <defaultValue xmi:type="expression:Expression" xmi:id="_33KpwWsOEeuWI54NqObC_w" name="isFalta1Cont" content="isFalta1Cont" type="TYPE_CONTRACT_INPUT" returnType="java.lang.Boolean">
          <referencedElements xmi:type="process:ContractInput" xmi:id="_IUFvMGsPEeuWI54NqObC_w" name="isFalta1Cont" type="BOOLEAN">
            <mapping xmi:type="process:ContractInputMapping" xmi:id="_IUFvMWsPEeuWI54NqObC_w"/>
          </referencedElements>
        </defaultValue>
      </data>
      <data xmi:type="process:Data" xmi:id="_5Iqt4GsOEeuWI54NqObC_w" name="isFalta2" dataType="_HMxunFauEeuD6v1bYMZP8Q">
        <defaultValue xmi:type="expression:Expression" xmi:id="_5Iqt4WsOEeuWI54NqObC_w" name="isFalta2Cont" content="isFalta2Cont" type="TYPE_CONTRACT_INPUT" returnType="java.lang.Boolean">
          <referencedElements xmi:type="process:ContractInput" xmi:id="_JIC7sGsPEeuWI54NqObC_w" name="isFalta2Cont" type="BOOLEAN">
            <mapping xmi:type="process:ContractInputMapping" xmi:id="_JIC7sWsPEeuWI54NqObC_w"/>
          </referencedElements>
        </defaultValue>
      </data>
      <data xmi:type="process:Data" xmi:id="_6UQXQGsOEeuWI54NqObC_w" name="isFalta3" dataType="_HMxunFauEeuD6v1bYMZP8Q">
        <defaultValue xmi:type="expression:Expression" xmi:id="_6UQXQWsOEeuWI54NqObC_w" name="isFalta3Cont" content="isFalta3Cont" type="TYPE_CONTRACT_INPUT" returnType="java.lang.Boolean">
          <referencedElements xmi:type="process:ContractInput" xmi:id="_KHbVEGsPEeuWI54NqObC_w" name="isFalta3Cont" type="BOOLEAN">
            <mapping xmi:type="process:ContractInputMapping" xmi:id="_KHbVEWsPEeuWI54NqObC_w"/>
          </referencedElements>
        </defaultValue>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_HMxuhFauEeuD6v1bYMZP8Q">
        <targetForm xmi:type="expression:Expression" xmi:id="_NKVscGsPEeuWI54NqObC_w" name="InstanciarReagendar" content="9d5ecf90-cf09-47bf-9da2-580474e50a16" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_HMxuhlauEeuD6v1bYMZP8Q">
        <targetForm xmi:type="expression:Expression" xmi:id="_HMxuh1auEeuD6v1bYMZP8Q" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_HMxuiFauEeuD6v1bYMZP8Q" target="_WmVwQGgDEeuSjcrVjSooiw" source="_HMxuc1auEeuD6v1bYMZP8Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_HMxuiVauEeuD6v1bYMZP8Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_HMxuilauEeuD6v1bYMZP8Q" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_TaP2gGc5EeuoDbTQ9HEyNA" target="_XPDWEGgDEeuSjcrVjSooiw" source="_WmVwQGgDEeuSjcrVjSooiw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_TaQdkGc5EeuoDbTQ9HEyNA"/>
        <condition xmi:type="expression:Expression" xmi:id="_TaQdkWc5EeuoDbTQ9HEyNA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_NWr4oGsKEeuWI54NqObC_w" target="_VaTXgGsPEeuWI54NqObC_w" source="_MmbgYGsKEeuWI54NqObC_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_NWsfsGsKEeuWI54NqObC_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_NWsfsWsKEeuWI54NqObC_w" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_PXONAGsKEeuWI54NqObC_w" target="_b_HIUGsPEeuWI54NqObC_w" source="_O8D7AGsKEeuWI54NqObC_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_PXO0EGsKEeuWI54NqObC_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_PXO0EWsKEeuWI54NqObC_w" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RcWtgGsKEeuWI54NqObC_w" target="_foDk8GsPEeuWI54NqObC_w" source="_QLqhsGsKEeuWI54NqObC_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RcXUkGsKEeuWI54NqObC_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_RcXUkWsKEeuWI54NqObC_w" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_S1TdcGsKEeuWI54NqObC_w" target="_S1MvwGsKEeuWI54NqObC_w" source="_OGIbwGsOEeuWI54NqObC_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_S1TdcWsKEeuWI54NqObC_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_S1TdcmsKEeuWI54NqObC_w" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Eb81cGsOEeuWI54NqObC_w" target="_La0sEGsOEeuWI54NqObC_w" source="_XPDWEGgDEeuSjcrVjSooiw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Eb81cWsOEeuWI54NqObC_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_Eb81cmsOEeuWI54NqObC_w" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_F9sVAGsOEeuWI54NqObC_w" target="_La0sEGsOEeuWI54NqObC_w" source="_PsyNUGsKEeuWI54NqObC_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_F9s8EGsOEeuWI54NqObC_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_F9s8EWsOEeuWI54NqObC_w" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Hj9vQGsOEeuWI54NqObC_w" target="_La0sEGsOEeuWI54NqObC_w" source="_Ogk44GsKEeuWI54NqObC_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Hj9vQWsOEeuWI54NqObC_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_Hj9vQmsOEeuWI54NqObC_w" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ItOdYGsOEeuWI54NqObC_w" target="_Nr4IsGsOEeuWI54NqObC_w" source="_La0sEGsOEeuWI54NqObC_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ItPrgGsOEeuWI54NqObC_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_ItPrgWsOEeuWI54NqObC_w" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_MydNYGsOEeuWI54NqObC_w" target="_MyaKEGsOEeuWI54NqObC_w" source="_Nr4IsGsOEeuWI54NqObC_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_MydNYWsOEeuWI54NqObC_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_MydNYmsOEeuWI54NqObC_w" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_sXZa0GsOEeuWI54NqObC_w" target="_sXStIGsOEeuWI54NqObC_w" source="_pVvAoGsOEeuWI54NqObC_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_sXZa0WsOEeuWI54NqObC_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_sXZa0msOEeuWI54NqObC_w" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_VangkGsPEeuWI54NqObC_w" target="_Ogk44GsKEeuWI54NqObC_w" source="_VaTXgGsPEeuWI54NqObC_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_VangkWsPEeuWI54NqObC_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_VangkmsPEeuWI54NqObC_w" name="newScript()" content="return isFalta1;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_D7kaUGsQEeuWI54NqObC_w" name="isFalta1" dataType="_HMxunFauEeuD6v1bYMZP8Q"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_aEz-0GsPEeuWI54NqObC_w" target="_aEsqEGsPEeuWI54NqObC_w" source="_VaTXgGsPEeuWI54NqObC_w" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_aEz-0WsPEeuWI54NqObC_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_aEz-0msPEeuWI54NqObC_w" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_b_LZwGsPEeuWI54NqObC_w" target="_PsyNUGsKEeuWI54NqObC_w" source="_b_HIUGsPEeuWI54NqObC_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_b_MA0GsPEeuWI54NqObC_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_b_MA0WsPEeuWI54NqObC_w" name="newScript()" content="return isFalta2;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_GnuekGsQEeuWI54NqObC_w" name="isFalta2" dataType="_HMxunFauEeuD6v1bYMZP8Q"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_dd1wIGsPEeuWI54NqObC_w" target="_ddvpgGsPEeuWI54NqObC_w" source="_b_HIUGsPEeuWI54NqObC_w" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_dd1wIWsPEeuWI54NqObC_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_dd1wImsPEeuWI54NqObC_w" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_foGoQGsPEeuWI54NqObC_w" target="_OGIbwGsOEeuWI54NqObC_w" source="_foDk8GsPEeuWI54NqObC_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_foGoQWsPEeuWI54NqObC_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_foGoQmsPEeuWI54NqObC_w" name="newScript()" content="return isFalta3;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_Iy8Y8GsQEeuWI54NqObC_w" name="isFalta3" dataType="_HMxunFauEeuD6v1bYMZP8Q"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_gmRgsGsPEeuWI54NqObC_w" target="_gl5tQGsPEeuWI54NqObC_w" source="_foDk8GsPEeuWI54NqObC_w" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_gmRgsWsPEeuWI54NqObC_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_gmRgsmsPEeuWI54NqObC_w" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0ck8wGsPEeuWI54NqObC_w" target="_pVvAoGsOEeuWI54NqObC_w" source="_z2MSMGsPEeuWI54NqObC_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0ck8wWsPEeuWI54NqObC_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_0ck8wmsPEeuWI54NqObC_w" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_HMxui1auEeuD6v1bYMZP8Q" documentation="Este es un ejemplo de actor que está mapeado a cualquier usuario de la organización ACME" name="Employee actor" initiator="true"/>
      <configurations xmi:type="configuration:Configuration" xmi:id="_cEUTIFawEeugyv-Gjc9f2Q" name="Qualification" version="7.11.1-001" username="Administrador" password="bpm">
        <actorMappings xmi:type="actormapping:ActorMappingsType" xmi:id="_cEU6MFawEeugyv-Gjc9f2Q">
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_cEU6MVawEeugyv-Gjc9f2Q" name="Employee actor">
            <groups xmi:type="actormapping:Groups" xmi:id="_cEU6MlawEeugyv-Gjc9f2Q">
              <group>/ADMINISTRADOR</group>
              <group>/ASPIRANTE</group>
              <group>/CAMPUS-CANCUN</group>
              <group>/CAMPUS-CORDOBA</group>
              <group>/CAMPUS-JP2</group>
              <group>/CAMPUS-MAYAB</group>
              <group>/CAMPUS-MNORTE</group>
              <group>/CAMPUS-MSUR</group>
              <group>/CAMPUS-OAXACA</group>
              <group>/CAMPUS-PUEBLA</group>
              <group>/CAMPUS-QUERETARO</group>
              <group>/CAMPUS-XALAPA</group>
              <group>/EXTERIOR</group>
              <group>/SERUA</group>
            </groups>
            <memberships xmi:type="actormapping:Membership" xmi:id="_cEU6M1awEeugyv-Gjc9f2Q"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_cEU6NFawEeugyv-Gjc9f2Q"/>
            <users xmi:type="actormapping:Users" xmi:id="_cEU6NVawEeugyv-Gjc9f2Q"/>
          </actorMapping>
        </actorMappings>
        <definitionMappings xmi:type="configuration:DefinitionMapping" xmi:id="_fNfawGsNEeuWI54NqObC_w" type="CONNECTOR" definitionId="rest-post" definitionVersion="1.1.0" implementationId="rest-post-impl" implementationVersion="1.0.7"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_cEUTIVawEeugyv-Gjc9f2Q" id="ACTOR_FILTER"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_cEUTIlawEeugyv-Gjc9f2Q" id="CONNECTOR">
          <children xmi:type="configuration:FragmentContainer" xmi:id="_fOoDMGsNEeuWI54NqObC_w" id="rest-post-impl-1.0.7">
            <fragments xmi:type="configuration:Fragment" xmi:id="_fO3TwGsNEeuWI54NqObC_w" key="rest-post-impl -- 1.0.7" value="bonita-connector-rest-1.0.7.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_fO360GsNEeuWI54NqObC_w" key="rest-post-impl -- 1.0.7" value="httpcore-4.3.3.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_fO4h4GsNEeuWI54NqObC_w" key="rest-post-impl -- 1.0.7" value="httpclient-4.3.6.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_fO5wAGsNEeuWI54NqObC_w" key="rest-post-impl -- 1.0.7" value="guava-18.0.jar" type="CONNECTOR"/>
          </children>
        </processDependencies>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_cEUTI1awEeugyv-Gjc9f2Q" id="GROOVY_SCRIPT"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_cEUTJFawEeugyv-Gjc9f2Q" id="OTHER"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_cEUTJVawEeugyv-Gjc9f2Q" id="GROOVY_SCRIPT"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_cEUTJlawEeugyv-Gjc9f2Q" id="OTHER"/>
      </configurations>
      <contract xmi:type="process:Contract" xmi:id="_HMxujFauEeuD6v1bYMZP8Q">
        <inputs xmi:type="process:ContractInput" xmi:id="_cyZYsGsKEeuWI54NqObC_w" name="usernameCont">
          <mapping xmi:type="process:ContractInputMapping" xmi:id="_cyZYsWsKEeuWI54NqObC_w"/>
        </inputs>
        <inputs xmi:type="process:ContractInput" xmi:id="_8deGgGsOEeuWI54NqObC_w" name="isFalta1Cont" type="BOOLEAN">
          <mapping xmi:type="process:ContractInputMapping" xmi:id="_8deGgWsOEeuWI54NqObC_w"/>
        </inputs>
        <inputs xmi:type="process:ContractInput" xmi:id="_9h2UoGsOEeuWI54NqObC_w" name="isFalta2Cont" type="BOOLEAN">
          <mapping xmi:type="process:ContractInputMapping" xmi:id="_9h2UoWsOEeuWI54NqObC_w"/>
        </inputs>
        <inputs xmi:type="process:ContractInput" xmi:id="_-pKiAGsOEeuWI54NqObC_w" name="isFalta3Cont" type="BOOLEAN">
          <mapping xmi:type="process:ContractInputMapping" xmi:id="_-pKiAWsOEeuWI54NqObC_w"/>
        </inputs>
      </contract>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_HMxujVauEeuD6v1bYMZP8Q">
        <name xmi:type="expression:Expression" xmi:id="_HMxujlauEeuD6v1bYMZP8Q" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_HMxuj1auEeuD6v1bYMZP8Q" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_HMxukFauEeuD6v1bYMZP8Q">
        <name xmi:type="expression:Expression" xmi:id="_HMxukVauEeuD6v1bYMZP8Q" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_HMxuklauEeuD6v1bYMZP8Q" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_HMxuk1auEeuD6v1bYMZP8Q">
        <name xmi:type="expression:Expression" xmi:id="_HMxulFauEeuD6v1bYMZP8Q" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_HMxulVauEeuD6v1bYMZP8Q" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_HMxullauEeuD6v1bYMZP8Q">
        <name xmi:type="expression:Expression" xmi:id="_HMxul1auEeuD6v1bYMZP8Q" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_HMxumFauEeuD6v1bYMZP8Q" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_HMxumVauEeuD6v1bYMZP8Q">
        <name xmi:type="expression:Expression" xmi:id="_HMxumlauEeuD6v1bYMZP8Q" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_HMxum1auEeuD6v1bYMZP8Q" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_HMxunFauEeuD6v1bYMZP8Q" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_HMxunVauEeuD6v1bYMZP8Q" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_HMxunlauEeuD6v1bYMZP8Q" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_HMxun1auEeuD6v1bYMZP8Q" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_HMxuoFauEeuD6v1bYMZP8Q" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_HMxuoVauEeuD6v1bYMZP8Q" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_HMxuolauEeuD6v1bYMZP8Q" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_HMxuo1auEeuD6v1bYMZP8Q" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_HMxupFauEeuD6v1bYMZP8Q" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_HMyVgFauEeuD6v1bYMZP8Q" type="Process" element="_HMxucFauEeuD6v1bYMZP8Q" name="MiDiagrama" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_HMyVgVauEeuD6v1bYMZP8Q" type="2007" element="_HMxucVauEeuD6v1bYMZP8Q">
      <children xmi:type="notation:DecorationNode" xmi:id="_HMyVglauEeuD6v1bYMZP8Q" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_HMyVg1auEeuD6v1bYMZP8Q" type="7001">
        <children xmi:type="notation:Node" xmi:id="_HMyVhFauEeuD6v1bYMZP8Q" type="3007" element="_HMxuclauEeuD6v1bYMZP8Q">
          <children xmi:type="notation:DecorationNode" xmi:id="_HMyVhVauEeuD6v1bYMZP8Q" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_HMyVhlauEeuD6v1bYMZP8Q" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_HMyVilauEeuD6v1bYMZP8Q" type="3002" element="_HMxuc1auEeuD6v1bYMZP8Q" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_HMyVi1auEeuD6v1bYMZP8Q" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_HMyVjFauEeuD6v1bYMZP8Q" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_HMyVjVauEeuD6v1bYMZP8Q" x="60" y="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_WmsVkGgDEeuSjcrVjSooiw" type="3027" element="_WmVwQGgDEeuSjcrVjSooiw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_WmuKwGgDEeuSjcrVjSooiw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_WmsVkWgDEeuSjcrVjSooiw" x="160" y="60" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_XPFLQGgDEeuSjcrVjSooiw" type="3005" element="_XPDWEGgDEeuSjcrVjSooiw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_XPFLQmgDEeuSjcrVjSooiw" type="5005"/>
              <children xmi:type="notation:Shape" xmi:id="_MmntoGsKEeuWI54NqObC_w" type="3043" element="_MmbgYGsKEeuWI54NqObC_w" fontName="Segoe UI">
                <children xmi:type="notation:DecorationNode" xmi:id="_Mmo7wGsKEeuWI54NqObC_w" type="5055">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_Mmo7wWsKEeuWI54NqObC_w" y="5"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_MmntoWsKEeuWI54NqObC_w" x="37" y="42"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_XPFLQWgDEeuSjcrVjSooiw" x="333" y="58"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_OgmHA2sKEeuWI54NqObC_w" type="3005" element="_Ogk44GsKEeuWI54NqObC_w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_OgmuEGsKEeuWI54NqObC_w" type="5005"/>
              <children xmi:type="notation:Shape" xmi:id="_O8EiEGsKEeuWI54NqObC_w" type="3043" element="_O8D7AGsKEeuWI54NqObC_w" fontName="Segoe UI">
                <children xmi:type="notation:DecorationNode" xmi:id="_O8FJIGsKEeuWI54NqObC_w" type="5055">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_O8FJIWsKEeuWI54NqObC_w" y="5"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_O8EiEWsKEeuWI54NqObC_w" x="37" y="42"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_OgmHBGsKEeuWI54NqObC_w" x="333" y="223" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Psy0YGsKEeuWI54NqObC_w" type="3005" element="_PsyNUGsKEeuWI54NqObC_w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Psy0YmsKEeuWI54NqObC_w" type="5005"/>
              <children xmi:type="notation:Shape" xmi:id="_QLrIwGsKEeuWI54NqObC_w" type="3043" element="_QLqhsGsKEeuWI54NqObC_w" fontName="Segoe UI">
                <children xmi:type="notation:DecorationNode" xmi:id="_QLrIwmsKEeuWI54NqObC_w" type="5055">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_QLrIw2sKEeuWI54NqObC_w" y="5"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_QLrIwWsKEeuWI54NqObC_w" x="37" y="42"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Psy0YWsKEeuWI54NqObC_w" x="333" y="385" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_S1N94GsKEeuWI54NqObC_w" type="3062" element="_S1MvwGsKEeuWI54NqObC_w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_S1N94msKEeuWI54NqObC_w" type="5090">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_S1N942sKEeuWI54NqObC_w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_S1N94WsKEeuWI54NqObC_w" x="816" y="490"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_La1TI2sOEeuWI54NqObC_w" type="3008" element="_La0sEGsOEeuWI54NqObC_w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_La16MGsOEeuWI54NqObC_w" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_La16MWsOEeuWI54NqObC_w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_La1TJGsOEeuWI54NqObC_w" x="503" y="226" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_MyaxIGsOEeuWI54NqObC_w" type="3062" element="_MyaKEGsOEeuWI54NqObC_w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_MyaxImsOEeuWI54NqObC_w" type="5090">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_MyaxI2sOEeuWI54NqObC_w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_MyaxIWsOEeuWI54NqObC_w" x="816" y="233"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Nr5W0GsOEeuWI54NqObC_w" type="3005" element="_Nr4IsGsOEeuWI54NqObC_w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Nr5W0msOEeuWI54NqObC_w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Nr5W0WsOEeuWI54NqObC_w" x="612" y="223" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_OGIbzWsOEeuWI54NqObC_w" type="3005" element="_OGIbwGsOEeuWI54NqObC_w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_OGJC0GsOEeuWI54NqObC_w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_OGIbzmsOEeuWI54NqObC_w" x="612" y="480" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_pVvnsGsOEeuWI54NqObC_w" type="3027" element="_pVvAoGsOEeuWI54NqObC_w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_pVvnsmsOEeuWI54NqObC_w" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_pVvnsWsOEeuWI54NqObC_w" x="612" y="613"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_sXTUMGsOEeuWI54NqObC_w" type="3062" element="_sXStIGsOEeuWI54NqObC_w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_sXTUMmsOEeuWI54NqObC_w" type="5090">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_sXTUM2sOEeuWI54NqObC_w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_sXTUMWsOEeuWI54NqObC_w" x="816" y="623"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_VaT-kGsPEeuWI54NqObC_w" type="3008" element="_VaTXgGsPEeuWI54NqObC_w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_VaT-kmsPEeuWI54NqObC_w" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_VaT-k2sPEeuWI54NqObC_w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_VaT-kWsPEeuWI54NqObC_w" x="361" y="154"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_aEtRI2sPEeuWI54NqObC_w" type="3018" element="_aEsqEGsPEeuWI54NqObC_w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_aEt4MGsPEeuWI54NqObC_w" type="5033">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_aEt4MWsPEeuWI54NqObC_w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_aEtRJGsPEeuWI54NqObC_w" x="186" y="159"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_b_HvYGsPEeuWI54NqObC_w" type="3008" element="_b_HIUGsPEeuWI54NqObC_w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_b_HvYmsPEeuWI54NqObC_w" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_b_HvY2sPEeuWI54NqObC_w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_b_HvYWsPEeuWI54NqObC_w" x="361" y="310"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ddvphGsPEeuWI54NqObC_w" type="3018" element="_ddvpgGsPEeuWI54NqObC_w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_ddvphmsPEeuWI54NqObC_w" type="5033">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_ddvph2sPEeuWI54NqObC_w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ddvphWsPEeuWI54NqObC_w" x="185" y="316"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_foEMAGsPEeuWI54NqObC_w" type="3008" element="_foDk8GsPEeuWI54NqObC_w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_foEMAmsPEeuWI54NqObC_w" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_foEMA2sPEeuWI54NqObC_w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_foEMAWsPEeuWI54NqObC_w" x="361" y="483"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_gl6UUmsPEeuWI54NqObC_w" type="3018" element="_gl5tQGsPEeuWI54NqObC_w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_gl67YGsPEeuWI54NqObC_w" type="5033">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_gl67YWsPEeuWI54NqObC_w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_gl6UU2sPEeuWI54NqObC_w" x="185" y="488"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_z2NgUGsPEeuWI54NqObC_w" type="3019" element="_z2MSMGsPEeuWI54NqObC_w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_z2NgUmsPEeuWI54NqObC_w" type="5034">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_z2NgU2sPEeuWI54NqObC_w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_z2NgUWsPEeuWI54NqObC_w" x="366" y="621"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_HMyVjlauEeuD6v1bYMZP8Q"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_HMyVj1auEeuD6v1bYMZP8Q" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_HMyVkFauEeuD6v1bYMZP8Q"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_HMyVkVauEeuD6v1bYMZP8Q"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_HMyVklauEeuD6v1bYMZP8Q" x="23" width="1297" height="726"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_HMyVk1auEeuD6v1bYMZP8Q"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_HMyVlFauEeuD6v1bYMZP8Q" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_HMyVlVauEeuD6v1bYMZP8Q"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_HMyVllauEeuD6v1bYMZP8Q"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_HMyVl1auEeuD6v1bYMZP8Q" width="1320" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_HMyVmFauEeuD6v1bYMZP8Q"/>
    <edges xmi:type="notation:Connector" xmi:id="_HMyVmVauEeuD6v1bYMZP8Q" type="4001" element="_HMxuiFauEeuD6v1bYMZP8Q" source="_HMyVilauEeuD6v1bYMZP8Q" target="_WmsVkGgDEeuSjcrVjSooiw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_HMyVmlauEeuD6v1bYMZP8Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_HMyVm1auEeuD6v1bYMZP8Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_HMyVnFauEeuD6v1bYMZP8Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_HMyVnVauEeuD6v1bYMZP8Q" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_TaQdkmc5EeuoDbTQ9HEyNA" type="4001" element="_TaP2gGc5EeuoDbTQ9HEyNA" source="_WmsVkGgDEeuSjcrVjSooiw" target="_XPFLQGgDEeuSjcrVjSooiw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_TaQdlWc5EeuoDbTQ9HEyNA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_TaQdlmc5EeuoDbTQ9HEyNA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_TaQdk2c5EeuoDbTQ9HEyNA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_TaQdlGc5EeuoDbTQ9HEyNA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_NWwKEGsKEeuWI54NqObC_w" type="4001" element="_NWr4oGsKEeuWI54NqObC_w" source="_MmntoGsKEeuWI54NqObC_w" target="_VaT-kGsPEeuWI54NqObC_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_NWxYMGsKEeuWI54NqObC_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_NWxYMWsKEeuWI54NqObC_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_NWwKEWsKEeuWI54NqObC_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_NWwKEmsKEeuWI54NqObC_w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_PXQCMGsKEeuWI54NqObC_w" type="4001" element="_PXONAGsKEeuWI54NqObC_w" source="_O8EiEGsKEeuWI54NqObC_w" target="_b_HvYGsPEeuWI54NqObC_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_PXQCM2sKEeuWI54NqObC_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_PXQCNGsKEeuWI54NqObC_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_PXQCMWsKEeuWI54NqObC_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_PXQCMmsKEeuWI54NqObC_w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RcYisGsKEeuWI54NqObC_w" type="4001" element="_RcWtgGsKEeuWI54NqObC_w" source="_QLrIwGsKEeuWI54NqObC_w" target="_foEMAGsPEeuWI54NqObC_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_RcYis2sKEeuWI54NqObC_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RcYitGsKEeuWI54NqObC_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RcYisWsKEeuWI54NqObC_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RcYismsKEeuWI54NqObC_w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_S1UEgGsKEeuWI54NqObC_w" type="4001" element="_S1TdcGsKEeuWI54NqObC_w" source="_OGIbzWsOEeuWI54NqObC_w" target="_S1N94GsKEeuWI54NqObC_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_S1UEg2sKEeuWI54NqObC_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_S1UEhGsKEeuWI54NqObC_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_S1UEgWsKEeuWI54NqObC_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_S1UEgmsKEeuWI54NqObC_w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Eb9cgGsOEeuWI54NqObC_w" type="4001" element="_Eb81cGsOEeuWI54NqObC_w" source="_XPFLQGgDEeuSjcrVjSooiw" target="_La1TI2sOEeuWI54NqObC_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Eb9cg2sOEeuWI54NqObC_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Eb9chGsOEeuWI54NqObC_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Eb9cgWsOEeuWI54NqObC_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Eb9cgmsOEeuWI54NqObC_w" points="[50, 0, -91, -112]$[141, 0, 0, -112]$[141, 91, 0, -21]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_F9s8EmsOEeuWI54NqObC_w" type="4001" element="_F9sVAGsOEeuWI54NqObC_w" source="_Psy0YGsKEeuWI54NqObC_w" target="_La1TI2sOEeuWI54NqObC_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_F9tjIGsOEeuWI54NqObC_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_F9tjIWsOEeuWI54NqObC_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_F9s8E2sOEeuWI54NqObC_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_F9s8FGsOEeuWI54NqObC_w" points="[0, -8, -89, 107]$[89, -8, 0, 107]$[89, -93, 0, 22]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_F9uxQGsOEeuWI54NqObC_w" id="(1.0,0.66)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Hj-WUGsOEeuWI54NqObC_w" type="4001" element="_Hj9vQGsOEeuWI54NqObC_w" source="_OgmHA2sKEeuWI54NqObC_w" target="_La1TI2sOEeuWI54NqObC_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Hj-WU2sOEeuWI54NqObC_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Hj-WVGsOEeuWI54NqObC_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Hj-WUWsOEeuWI54NqObC_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Hj-WUmsOEeuWI54NqObC_w" points="[0, 0, -90, 6]$[87, -24, -3, -18]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Hj_kcGsOEeuWI54NqObC_w" id="(1.0,0.62)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ItPrgmsOEeuWI54NqObC_w" type="4001" element="_ItOdYGsOEeuWI54NqObC_w" source="_La1TI2sOEeuWI54NqObC_w" target="_Nr5W0GsOEeuWI54NqObC_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ItPrhWsOEeuWI54NqObC_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ItPrhmsOEeuWI54NqObC_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ItPrg2sOEeuWI54NqObC_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ItPrhGsOEeuWI54NqObC_w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Myd0cGsOEeuWI54NqObC_w" type="4001" element="_MydNYGsOEeuWI54NqObC_w" source="_Nr5W0GsOEeuWI54NqObC_w" target="_MyaxIGsOEeuWI54NqObC_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Myd0c2sOEeuWI54NqObC_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Myd0dGsOEeuWI54NqObC_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Myd0cWsOEeuWI54NqObC_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Myd0cmsOEeuWI54NqObC_w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_sXaB4GsOEeuWI54NqObC_w" type="4001" element="_sXZa0GsOEeuWI54NqObC_w" source="_pVvnsGsOEeuWI54NqObC_w" target="_sXTUMGsOEeuWI54NqObC_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_sXaB42sOEeuWI54NqObC_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_sXaB5GsOEeuWI54NqObC_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_sXaB4WsOEeuWI54NqObC_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_sXaB4msOEeuWI54NqObC_w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Vangk2sPEeuWI54NqObC_w" type="4001" element="_VangkGsPEeuWI54NqObC_w" source="_VaT-kGsPEeuWI54NqObC_w" target="_OgmHA2sKEeuWI54NqObC_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_VaoHoGsPEeuWI54NqObC_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_VaoHoWsPEeuWI54NqObC_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_VanglGsPEeuWI54NqObC_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_VanglWsPEeuWI54NqObC_w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_aE4QQGsPEeuWI54NqObC_w" type="4001" element="_aEz-0GsPEeuWI54NqObC_w" source="_VaT-kGsPEeuWI54NqObC_w" target="_aEtRI2sPEeuWI54NqObC_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_aE4QQ2sPEeuWI54NqObC_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_aE43UGsPEeuWI54NqObC_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_aE4QQWsPEeuWI54NqObC_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_aE4QQmsPEeuWI54NqObC_w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_b_MA0msPEeuWI54NqObC_w" type="4001" element="_b_LZwGsPEeuWI54NqObC_w" source="_b_HvYGsPEeuWI54NqObC_w" target="_Psy0YGsKEeuWI54NqObC_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_b_MA1WsPEeuWI54NqObC_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_b_MA1msPEeuWI54NqObC_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_b_MA02sPEeuWI54NqObC_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_b_MA1GsPEeuWI54NqObC_w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_dd6ooGsPEeuWI54NqObC_w" type="4001" element="_dd1wIGsPEeuWI54NqObC_w" source="_b_HvYGsPEeuWI54NqObC_w" target="_ddvphGsPEeuWI54NqObC_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_dd6oo2sPEeuWI54NqObC_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_dd6opGsPEeuWI54NqObC_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_dd6ooWsPEeuWI54NqObC_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_dd6oomsPEeuWI54NqObC_w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_foGoQ2sPEeuWI54NqObC_w" type="4001" element="_foGoQGsPEeuWI54NqObC_w" source="_foEMAGsPEeuWI54NqObC_w" target="_OGIbzWsOEeuWI54NqObC_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_foGoRmsPEeuWI54NqObC_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_foGoR2sPEeuWI54NqObC_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_foGoRGsPEeuWI54NqObC_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_foGoRWsPEeuWI54NqObC_w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_gmVLEGsPEeuWI54NqObC_w" type="4001" element="_gmRgsGsPEeuWI54NqObC_w" source="_foEMAGsPEeuWI54NqObC_w" target="_gl6UUmsPEeuWI54NqObC_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_gmVLE2sPEeuWI54NqObC_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_gmVLFGsPEeuWI54NqObC_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_gmVLEWsPEeuWI54NqObC_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_gmVLEmsPEeuWI54NqObC_w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0clj0GsPEeuWI54NqObC_w" type="4001" element="_0ck8wGsPEeuWI54NqObC_w" source="_z2NgUGsPEeuWI54NqObC_w" target="_pVvnsGsOEeuWI54NqObC_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_0clj02sPEeuWI54NqObC_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0clj1GsPEeuWI54NqObC_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0clj0WsPEeuWI54NqObC_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0clj0msPEeuWI54NqObC_w" points="[-12, 0, -263, 19]$[201, -11, -50, 8]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_0cmx8GsPEeuWI54NqObC_w" id="(1.0,0.9411764705882353)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
